(load (concat eee-base-directory "add-ons/" "python-mode"))
(load (concat eee-base-directory "add-ons/" "string"))
(load (concat eee-base-directory "add-ons/" "jsx-mode"))


(load (concat eee-base-directory "eee-default-behaviour"))
(load (concat eee-base-directory "eee-keys"))
(load (concat eee-base-directory "eee-text"))
(load (concat eee-base-directory "eee-buffer"))
(load (concat eee-base-directory "eee-templates"))
(load (concat eee-base-directory "eee-templates-lisp"))
(load (concat eee-base-directory "eee-templates-lisp-eee"))
(load (concat eee-base-directory "eee-templates-c"))
(load (concat eee-base-directory "eee-templates-c-kernel"))
(load (concat eee-base-directory "eee-templates-c++"))
(load (concat eee-base-directory "eee-templates-c++-qt"))
(load (concat eee-base-directory "eee-templates-python"))
(load (concat eee-base-directory "eee-templates-perl"))
(load (concat eee-base-directory "eee-source-navigation"))
