(eee-templates:define-template-expansion "c" "kernelmodule"
    '( (0 "#include <linux/module.h>")
       (0 "#include <linux/kernel.h>")
       (0 "#include <linux/init.h>")
       (0 "")
       (0 "«moduleparms»")
       (0 "")
       (0 "static int __init «!modulename!»_init (void)")
       (0 "{")
       (1 "")
       (1 "return 0;")
       (0 "}")
       (0 "")
       (0 "static void __exit «!modulename!»_exit (void)")
       (0 "{")
       (1 "")
       (0 "}")
       (0 "")
       (0 "module_init(«!modulename!»_init);")
       (0 "module_exit(«!modulename!»_exit);")
       (0 "")
       (0 "MODULE_LICENSE(\"GPL\");")
       (0 "MODULE_AUTHOR(\"«!author!»\");")
       (0 "MODULE_DESCRIPTION(\"«!description!»\");")
     )
)

(eee-templates:define-template-expansion "c" "moduleparms"
    '( (0 "static «!type!» «!name!» = «!defaultvalue!»;")
       (0 "MODULE_PARM(«!name!», \"«!typecode!»\");")
       (0 "MODULE_PARM_DESC(«!name!», \"«!description!»\");")
       (0 "«moduleparms»")
     )
)
